version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "America/Bogota"

    open-pull-requests-limit: 5

    labels:
      - dependencies
      - backend

    commit-message:
      prefix: "deps"
      include: "scope"

    rebase-strategy: "auto"
