"""add two index

Revision ID: 18a348046803
Revises: da86bf9f5b9c
Create Date: 2026-01-16 06:40:03.891486

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18a348046803"
down_revision: Union[str, Sequence[str], None] = "da86bf9f5b9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_client_documentid"), "client", ["documentid"], unique=True)
    op.create_index(op.f("ix_client_email"), "client", ["email"], unique=True)
    op.create_index(op.f("ix_employee_documentid"), "employee", ["documentid"], unique=True)
    op.create_index(op.f("ix_employee_email"), "employee", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employee_email"), table_name="employee")
    op.drop_index(op.f("ix_employee_documentid"), table_name="employee")
    op.drop_index(op.f("ix_client_email"), table_name="client")
    op.drop_index(op.f("ix_client_documentid"), table_name="client")
    # ### end Alembic commands ###
