"""fix product_category cascade and indexes

Revision ID: 633c72a87f5a
Revises: 18a348046803
Create Date: 2026-02-17 15:35:57.716163

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "633c72a87f5a"
down_revision: Union[str, Sequence[str], None] = "18a348046803"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_productcategory_category_id"), table_name="productcategory")
    op.drop_index(op.f("ix_productcategory_product_id"), table_name="productcategory")
    op.drop_constraint(
        op.f("productcategory_category_id_fkey"), "productcategory", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("productcategory_product_id_fkey"), "productcategory", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "productcategory", "product", ["product_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "productcategory", "category", ["category_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "productcategory", type_="foreignkey")
    op.drop_constraint(None, "productcategory", type_="foreignkey")
    op.create_foreign_key(
        op.f("productcategory_product_id_fkey"),
        "productcategory",
        "product",
        ["product_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("productcategory_category_id_fkey"),
        "productcategory",
        "category",
        ["category_id"],
        ["id"],
    )
    op.create_index(
        op.f("ix_productcategory_product_id"), "productcategory", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_productcategory_category_id"), "productcategory", ["category_id"], unique=False
    )
    # ### end Alembic commands ###
