"""fix product_category category index

Revision ID: e2419455572d
Revises: 633c72a87f5a
Create Date: 2026-02-17 15:41:35.274500

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2419455572d"
down_revision: Union[str, Sequence[str], None] = "633c72a87f5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_pc_category_id", "productcategory", ["category_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pc_category_id", table_name="productcategory")
    # ### end Alembic commands ###
