"""add is_verified attribute

Revision ID: 09dd04194263
Revises: 96d4ea3425d7
Create Date: 2026-02-20 00:36:23.443295

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09dd04194263"
down_revision: Union[str, Sequence[str], None] = "96d4ea3425d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employee", sa.Column("is_verified", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee", "is_verified")
    # ### end Alembic commands ###
