"""cascade delete payments on client delete

Revision ID: 96d4ea3425d7
Revises: ee6e7a2f2b56
Create Date: 2026-02-17 16:39:15.023510

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96d4ea3425d7"
down_revision: Union[str, Sequence[str], None] = "ee6e7a2f2b56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("payment_client_id_fkey"), "payment", type_="foreignkey")
    op.create_foreign_key(None, "payment", "client", ["client_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payment", type_="foreignkey")
    op.create_foreign_key(
        op.f("payment_client_id_fkey"), "payment", "client", ["client_id"], ["id"]
    )
    # ### end Alembic commands ###
