"""cascade delete order products and services

Revision ID: ae18940c7534
Revises: e2419455572d
Create Date: 2026-02-17 15:55:19.623390

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae18940c7534"
down_revision: Union[str, Sequence[str], None] = "e2419455572d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("orderproduct_order_id_fkey"), "orderproduct", type_="foreignkey")
    op.create_foreign_key(None, "orderproduct", "order", ["order_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("orderservice_order_id_fkey"), "orderservice", type_="foreignkey")
    op.create_foreign_key(None, "orderservice", "order", ["order_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orderservice", type_="foreignkey")
    op.create_foreign_key(
        op.f("orderservice_order_id_fkey"), "orderservice", "order", ["order_id"], ["id"]
    )
    op.drop_constraint(None, "orderproduct", type_="foreignkey")
    op.create_foreign_key(
        op.f("orderproduct_order_id_fkey"), "orderproduct", "order", ["order_id"], ["id"]
    )
    # ### end Alembic commands ###
