"""Modified Employee table

Revision ID: c7dd19dc2cb9
Revises: 09dd04194263
Create Date: 2026-03-06 01:41:18.677468

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c7dd19dc2cb9"
down_revision: Union[str, Sequence[str], None] = "09dd04194263"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee", sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column("employee", sa.Column("profile_completed", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_employee_user_id"), "employee", ["user_id"], unique=True)
    op.drop_column("employee", "provider")
    op.drop_column("employee", "provider_id")
    op.drop_column("employee", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee", sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "employee", sa.Column("provider_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "employee",
        sa.Column(
            "provider",
            postgresql.ENUM("LOCAL", "GOOGLE", name="employeeprovider"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_employee_user_id"), table_name="employee")
    op.drop_column("employee", "profile_completed")
    op.drop_column("employee", "user_id")
    # ### end Alembic commands ###
