"""Init

Revision ID: da86bf9f5b9c
Revises:
Create Date: 2026-01-16 06:19:54.008714

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da86bf9f5b9c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True, autoincrement=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.create_table(
        "client",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True, autoincrement=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("documentid", sa.Integer(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
    )
    op.create_table(
        "employee",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True, autoincrement=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("documentid", sa.Integer(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=False),
        sa.Column("role", sa.Enum("ADMIN", "EMPLOYEE", name="employeerole"), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sa.Enum("LOCAL", "GOOGLE", name="employeeprovider"), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=True),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True, autoincrement=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("short_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column("minimum_stock", sa.Integer(), nullable=False),
        sa.Column("image_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
    )
    op.create_table(
        "service",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True, autoincrement=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("short_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
    )
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True, autoincrement=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPLETED", "CANCELLED", "REFUNDED", name="orderstatus"),
            nullable=False,
        ),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employee.id"],
        ),
    )
    op.create_index(op.f("ix_order_client_id"), "order", ["client_id"], unique=False)
    op.create_index(op.f("ix_order_employee_id"), "order", ["employee_id"], unique=False)
    op.create_table(
        "payment",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True, autoincrement=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column(
            "method",
            sa.Enum("CASH", "BANK_TRANSFER", "ON_CREDIT", name="paymentmethod"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPLETED", "FAILED", "REFUNDED", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("interest_rate", sa.Float(), nullable=True),
        sa.Column("account_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
        ),
    )
    op.create_index(op.f("ix_payment_client_id"), "payment", ["client_id"], unique=False)
    op.create_table(
        "productcategory",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("product_id", "category_id"),
    )
    op.create_index(
        op.f("ix_productcategory_category_id"), "productcategory", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_productcategory_product_id"), "productcategory", ["product_id"], unique=False
    )
    op.create_table(
        "serviceinput",
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["service.id"],
        ),
        sa.PrimaryKeyConstraint("service_id", "product_id"),
    )
    op.create_index(
        op.f("ix_serviceinput_product_id"), "serviceinput", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_serviceinput_service_id"), "serviceinput", ["service_id"], unique=False
    )
    op.create_table(
        "orderproduct",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("order_id", "product_id"),
    )
    op.create_index(op.f("ix_orderproduct_order_id"), "orderproduct", ["order_id"], unique=False)
    op.create_index(
        op.f("ix_orderproduct_product_id"), "orderproduct", ["product_id"], unique=False
    )
    op.create_table(
        "orderservice",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["service.id"],
        ),
        sa.PrimaryKeyConstraint("order_id", "service_id"),
    )
    op.create_index(op.f("ix_orderservice_order_id"), "orderservice", ["order_id"], unique=False)
    op.create_index(
        op.f("ix_orderservice_service_id"), "orderservice", ["service_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orderservice_service_id"), table_name="orderservice")
    op.drop_index(op.f("ix_orderservice_order_id"), table_name="orderservice")
    op.drop_table("orderservice")
    op.drop_index(op.f("ix_orderproduct_product_id"), table_name="orderproduct")
    op.drop_index(op.f("ix_orderproduct_order_id"), table_name="orderproduct")
    op.drop_table("orderproduct")
    op.drop_index(op.f("ix_serviceinput_service_id"), table_name="serviceinput")
    op.drop_index(op.f("ix_serviceinput_product_id"), table_name="serviceinput")
    op.drop_table("serviceinput")
    op.drop_index(op.f("ix_productcategory_product_id"), table_name="productcategory")
    op.drop_index(op.f("ix_productcategory_category_id"), table_name="productcategory")
    op.drop_table("productcategory")
    op.drop_index(op.f("ix_payment_client_id"), table_name="payment")
    op.drop_table("payment")
    op.drop_index(op.f("ix_order_employee_id"), table_name="order")
    op.drop_index(op.f("ix_order_client_id"), table_name="order")
    op.drop_table("order")
    op.drop_table("service")
    op.drop_table("product")
    op.drop_table("employee")
    op.drop_table("client")
    op.drop_table("category")
    # ### end Alembic commands ###
