"""add alert models

Revision ID: de13bc3d81ac
Revises: f8c2b0b4b3e1
Create Date: 2026-03-14 18:04:17.328244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de13bc3d81ac'
down_revision: Union[str, Sequence[str], None] = 'f8c2b0b4b3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expirationalert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expiration_alerts_notified_false', 'expirationalert', ['product_id'], unique=False, postgresql_where=sa.text('notified = false'))
    op.create_table('stockalert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('minimum_stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_alerts_notified_false', 'stockalert', ['product_id'], unique=False, postgresql_where=sa.text('notified = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_alerts_notified_false', table_name='stockalert', postgresql_where=sa.text('notified = false'))
    op.drop_table('stockalert')
    op.drop_index('idx_expiration_alerts_notified_false', table_name='expirationalert', postgresql_where=sa.text('notified = false'))
    op.drop_table('expirationalert')
    # ### end Alembic commands ###
