"""cascade delete service inputs

Revision ID: ee6e7a2f2b56
Revises: ae18940c7534
Create Date: 2026-02-17 16:30:55.444010

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee6e7a2f2b56"
down_revision: Union[str, Sequence[str], None] = "ae18940c7534"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_serviceinput_product_id"), table_name="serviceinput")
    op.drop_index(op.f("ix_serviceinput_service_id"), table_name="serviceinput")
    op.create_index("ix_si_product_id", "serviceinput", ["product_id"], unique=False)
    op.drop_constraint(op.f("serviceinput_product_id_fkey"), "serviceinput", type_="foreignkey")
    op.drop_constraint(op.f("serviceinput_service_id_fkey"), "serviceinput", type_="foreignkey")
    op.create_foreign_key(
        None, "serviceinput", "service", ["service_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "serviceinput", "product", ["product_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "serviceinput", type_="foreignkey")
    op.drop_constraint(None, "serviceinput", type_="foreignkey")
    op.create_foreign_key(
        op.f("serviceinput_service_id_fkey"), "serviceinput", "service", ["service_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("serviceinput_product_id_fkey"), "serviceinput", "product", ["product_id"], ["id"]
    )
    op.drop_index("ix_si_product_id", table_name="serviceinput")
    op.create_index(
        op.f("ix_serviceinput_service_id"), "serviceinput", ["service_id"], unique=False
    )
    op.create_index(
        op.f("ix_serviceinput_product_id"), "serviceinput", ["product_id"], unique=False
    )
    # ### end Alembic commands ###
